Fix for small sample, bring arguments to MFF
sakaiando/macroframe-forecast pull request #31
Opened 2024-12-17 22:52 UTC by ShuvamDasWork

- When observations available for training are less than or equal to 15, Elastic Net doesn't work. Therefore, the original DefaultForecaster function is modified to have a parameter small_sample, which when set to True, dropes ElasticNetcv from the list of models to be used in the gridsearch algorithm. In case the number of observations for training are less than or equal to 10, all models give errors, and therefore MFF is modified to give None in this case.

- Brought up arguments from functions to MFF.

2024-12-19 12:47 UTC, SultanOrazbayevWork reviewed
Just a few small points for discussion.

2024-12-19 12:47 UTC, SultanOrazbayevWork commented on mff/MFF.py
>                   forecaster = DefaultForecaster(),
Consider adding a type hint here:

```suggestion
                 forecaster: BaseForecaster = DefaultForecaster(),
```

Kindly note that also you'll need to have the relevant import statement in this file:

```
from sktime.forecasting.base import BaseForecaster
```

2024-12-19 12:47 UTC, SultanOrazbayevWork commented on mff/MFF.py
> +        Indicate whether the smoothness paramatere lambda is to be calculated
```suggestion
        Indicate whether the smoothness paramater lambda is to be calculated
```

2024-12-19 12:47 UTC, SultanOrazbayevWork commented on mff/MFF.py
> +    default_lam : float, optional(default: 6.25)
I think it's possible to combine `lamstar_empirically` and `default_lam`. So, e.g. if `default_lam` is 0 or -1, then the lambda is calculated empirically...

2025-01-03 15:06 UTC, ShuvamDasWork commented on mff/MFF.py
> +    default_lam : float, optional(default: 6.25)
This has been done. Now default_lam = -1 signals lambda is to be calculated empirically.

2025-01-03 15:41 UTC, sakaiando commented on mff/utils.py
> +        gscv = YfromX(LinearRegression(fit_intercept = False))
I wonder whether LinearRegression should be replaced by ols_pca since the former may suffer from multicolinearity when the dimension of X is large.

2025-01-03 16:12 UTC, sakaiando commented on mff/MFF.py
> +        forecaster = ForecasterSetup(forecaster = forecaster,
ForecasterSetup does two things: checks sample size and choose forecaster

It might be cleaner to separate them into
small_sample:bool = CheckTrainingSampleSize(df0,n_forecast_error)
and
Default_Forecaster(small_sample)

What do you think?

2025-01-04 08:17 UTC, SultanOrazbayevWork commented on mff/MFF.py
> +            return(None)
Putting the condition inside `CheckTrainingSampleSize` is a good idea. Inside it, it might be a good idea to raise an explicit error, rather than returning None. Roughly:

```python
class InsufficientObservationCount(Exception):
   """Raised when the observation count is not sufficiently large."""

if n<10:
   raise InsufficientObservationCount()
```

The naming and messages are tentative.

2025-01-04 08:18 UTC, SultanOrazbayevWork commented on mff/utils.py
> +        gscv = YfromX(LinearRegression(fit_intercept = False))
The concern is legitimate, but I don't have a strong preference here.

2025-01-04 08:37 UTC, SultanOrazbayevWork commented on mff/MFF.py
> +        forecaster = ForecasterSetup(forecaster = forecaster,
Sounds like a good idea. The only suggestion is to use snake_case for function names and CapWords for classes. So, this would become `check_training_sample_size` for the function name.

2025-01-04 08:48 UTC, SultanOrazbayevWork requested changes
LGTM, subject to implementing Sakai's suggestion of raising an exception/error if sample size is too small.

2025-01-04 08:48 UTC, SultanOrazbayevWork commented on mff/tests/tests_MFF.py
General comment on the tests. Not for this PR, but it might be a good idea to track the actual expected results in the tests.

2025-01-06 11:52 UTC, ShuvamDasWork commented on mff/utils.py
> +        gscv = YfromX(LinearRegression(fit_intercept = False))
I agree, I have put in OLS PCA as the alternative. Happy to change to a different option, I als do not have a strong preference here for either.

2025-01-06 11:53 UTC, ShuvamDasWork commented on mff/MFF.py
> +            return(None)
Thanks both. @SultanOrazbayevWork using the class to show the exception is very useful, I have implemented it along the lines of your solution.

2025-01-07 13:20 UTC, merged